apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  db_user: YXBwMQ==
  db_password: QXBwUGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking-space
  template:
    metadata:
      labels:
        app: coworking-space
    spec:
      containers:
        - name: coworking-space
          image: 585237819899.dkr.ecr.us-east-1.amazonaws.com/coworking-space:latest
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: db_password
          ports:
            - containerPort: 5153
---
apiVersion: v1
kind: Service
metadata:
  name: coworking-space
spec:
  selector:
    app: coworking-space
  ports:
    - name: http
      port: 80
      targetPort: 5153
  type: LoadBalancer
