version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "coworking-space"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y zip
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - ECR_REGISTRY=$(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --region us-east-1 | jq -r ".repositories[0].registryId").dkr.ecr.us-east-1.amazonaws.com
    - DOCKER_LOGIN_COMMAND=$(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY)
    - if [ $? -ne 0 ]; then echo "Failed to execute docker login command"; exit 1; fi
  build:
    commands:
      - docker build -f analytics/Dockerfile -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $ECR_REGISTRY/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 585237819899.dkr.ecr.us-east-1.amazonaws.com
      - docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:latest