apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
data:
  cloudwatch-agent-config.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/coworking-space.log",
                "log_group_name": "coworking-space",
                "log_stream_name": "{instance_id}"
              }
            ]
          }
        }
      }
    }