apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: coworking-space
          image: 585237819899.dkr.ecr.us-east-1.amazonaws.com/coworking-space:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - name: ecr-registry-volume
              mountPath: /root/.docker/
      imagePullSecrets:
        - name: ecr-registry-secret
      volumes:
        - name: ecr-registry-volume
          secret:
            secretName: ecr-registry-secret
