apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking
  template:
    metadata:
      labels:
        app: coworking
    spec:
      containers:
        - name: coworking-space
          image: 585237819899.dkr.ecr.us-east-1.amazonaws.com/coworking:latest
          env:
          - name: APP_PORT
            value: "5000"
          - name: DB_USERNAME
            value: postgres
          - name: DB_HOST
            value: postgresql.default.svc.cluster.local
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password
          ports:
            - containerPort: 5000
          args: ["python", "app.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  selector:
    app: coworking
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
